package script.states;

public enum WithdrawBankingState {

    BANKING_COMPLETED,

    WITHDRAW_ITEMS,
    WITHDRAW_STAFF_OF_WATER,
    WITHDRAW_RING_OF_RECOIL,
    WITHDRAW_SAPPHIRE_RING,
    WITHDRAW_COSMIC_RUNE,
}
